### ISSUE TITLE
Improve Posting Creation Request and Category fields

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#130]
# Plan/Proposed Change
The Creation Screen currently has Switches for the Request and Category fields.
Either change these to dropdowns with the appropriate fields or add labels below switches to inform user what value they are selecting.

# Why is this important
Currently it is not completely clear what the values of the switches are. Need to make sure the user knows exactly what they are creating and the values associated.

# Additional Context/Questions
Values for Request are either: Offer or Request
Values for Category: Good or Service

To improve/facilitate searching by category, could provide a picker or TextInput for selecting a specific category for the posting to belong to. The Posting model on the backend already has a `category` field that takes a string value.

Might want to checkout the [react-native-picker](https://github.com/react-native-community/react-native-picker)

**Comment by SimonBartonPSU** [comment]
I believe I've got this functionality with my [commit](https://github.com/Capstone-SS-2020-PDX/Covid-19-MutualAid/commit/1d93d0ad6d89622cacbee514a372ba79b2b90620) on branch posting-creation-field-improvement. There is still a need to improve the styling. I can't figure out how to get the Pickers to collapse and not take up a crap-ton of room. If we can get the layout better, this may be good. Although, I also wonder if there are options other than Picker that would be better..... Not sure right now.

![picker](https://user-images.githubusercontent.com/46763450/86540249-8aca6000-beb8-11ea-8882-2af466ef31f9.jpg)

In any case, if anyone wants to try to still feel free to pull my branch and add a commit. Otherwise, I'll try to come back to this later today.

**Comment by SimonBartonPSU** [comment]
Hmmmm Picker does look good on Droid. This is yet another iOS needs special attention situation...

![droid_picker](https://user-images.githubusercontent.com/46763450/86541008-1e525f80-bebe-11ea-992f-f9e4b0d1b1e1.png)

**Comment by SimonBartonPSU** [comment]
Error mentioned in commit:

![IMG-1651](https://user-images.githubusercontent.com/46763450/86543249-ae4dd480-bed1-11ea-8db0-435c63f707d5.jpg)

**Comment by SimonBartonPSU** [comment]
Well I [tried again](https://github.com/Capstone-SS-2020-PDX/Covid-19-MutualAid/commit/c3fbf05595eeeeca1dbc06152ad66847284d6d9c) and still not dice... stuck with the above error still...

Somehow I'm returning null from my components??
