### ISSUE TITLE
Update Model and API with new Postings Fields

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#56]
# Plan/Proposed Change
Give postings:
- description: String
- is_service: char
- quantity: int fields

# Example Posting
Id: “X”
Title: “Spare tamales for the neighborhood”
Desc: “I’ve made 40 tamales, come grab one”
Quantity: 40
Is_service: g
“Created_on”: autogenerated

**Comment by SimonBartonPSU** [comment]
Looks like after yesterday we ended up with this for posting:
`       "id": 1,
        "title": "POSTMAN TEST, BABY",
        "desc": null,
        "count": 1,
        "category": null,
        "created_on": "2020-05-14",
        "owner": null`
so count is same as quantity and we have category instead of is_service, I think that makes sense because a posting could be a hybrid (e.g. I'll buy you groceries, _and_ I'll go get them and deliver them to your home)
Closed by #60
